name: grainlegumes-pino-dev
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.4
  - cpuonly
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - pyarrow
  - h5py
  - pyyaml
  - ipykernel
  - nbconvert
  - ipywidgets
  - ipython
  - pytest
  - ruff=0.15.11
  - mypy
  - radon
  - setuptools
  - wheel
  - pip
  - pip:
      - basedpyright
      - pandas-stubs
      - types-PyYAML
      - neuraloperator @ git+https://github.com/neuraloperator/neuraloperator.git@86a8bc7812a31b42c4f7895693cf4ac11521c066
      - optuna
      - wandb == 0.28.1
