name: grainlegumes-pino

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11

  # PyTorch / CUDA
  - pytorch=2.4
  - pytorch-cuda=12.1

  # Scientific stack
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - pyarrow
  - h5py
  - pyyaml

  # Interactive / notebooks
  - ipykernel
  - nbconvert
  - ipywidgets
  - ipython

  # Package build and pip dependencies
  - setuptools
  - wheel
  - pip
  - pip:
      - neuraloperator @ git+https://github.com/neuraloperator/neuraloperator.git@86a8bc7812a31b42c4f7895693cf4ac11521c066
      - optuna
      - wandb == 0.28.1
